const ReportDashboardPage=require('../../support/pageObjects/LMS/adminReportPage')

describe('Admin Report Validation',function(){

    beforeEach(function(){
      cy.visit(Cypress.env("url"))
      cy.viewport(1920,1080)
      cy.fixture("LMS/Credentials").then(function (validAdminLoginData) {
        cy.adminLogin(validAdminLoginData.username, validAdminLoginData.password)
    })

      cy.fixture('GradeBook_templateDetails').as('TemplateDetails')
    })

    it('Tc_001 Verify that School Admin can Edit the TopSchool Gradebook Template',function(){
        ReportDashboardPage.getAdminReportsSideMenubarReportTab().click()
        ReportDashboardPage.getAdminReportsStudentGradebookTab().should('be.visible',{timeout:2000}).click({force:true})
        ReportDashboardPage.getAdminReportsVerifyStudentGradebookText().should('have.text',this.TemplateDetails.StudentGradebookText)
        ReportDashboardPage.getAdminReportsGradeEditButton(this.TemplateDetails.Grade).click()
    
        ReportDashboardPage.getAdminReportsVerifyBasicTemplateDetailsText().should('have.text',this.TemplateDetails.BasicTemplateDetailsText)
        ReportDashboardPage.getCreateNewTemplateGradeDropdown().should('have.text',this.TemplateDetails.Grade)
        ReportDashboardPage.getCreateNewTemplateSectionDropdown().should('have.text',this.TemplateDetails.section)
        ReportDashboardPage.getCreateNewTemplateNumberOftermsDropdown().click()
        ReportDashboardPage.getCreateNewTemplateSelectNumberOftermsValue().click()
        ReportDashboardPage.getCreateNewTemplatePublishGradebookInDropdown().click()
        ReportDashboardPage.getCreateNewTemplateSelectPublishGradebookInValue().click({force:true})
        ReportDashboardPage.getCreateNewTemplateAddTestTypeButton().click()
        ReportDashboardPage.getDelButton().click()
        ReportDashboardPage.getCreateNewTemplateTermDropdown().click().wait(1000)
        ReportDashboardPage.getCreateNewTemplateTermCheckbox().dblclick()
        cy.get('body').click()
        ReportDashboardPage.getCreateNewTemplateTestTypeDropdown().click()
        ReportDashboardPage.getCreateNewTemplateSelectTestTypeValue().click()
        ReportDashboardPage.getCreateNewTemplateMaxMarksDropdown().click()
        ReportDashboardPage.getCreateNewTemplateSelectMaxMarksValue().click()

       ReportDashboardPage.getCreateNewTemplateAddSubjectButton().click()
       ReportDashboardPage.getCreateNewTemplateSubjectDropdown().click()
       ReportDashboardPage.getCreateNewTemplateSelectSubjectvalue().click()

       ReportDashboardPage.getCreateNewTemplateAddTheoryAndPracticleButton().click()
       ReportDashboardPage.getAddTheoryAndPracticleTestTypeDropdown().click({force:true})
       ReportDashboardPage.getAddTheoryAndPracticleTestTypeValue().click()
       ReportDashboardPage.getCreateNewTemplateTheoryTextfield().should('have.value',this.TemplateDetails.Theory)
       ReportDashboardPage.getCreateNewTemplatePracticleTextfield().click().type(this.TemplateDetails.Practicle)
       ReportDashboardPage.getCreateNewTemplateAddActivityTextfield().type(this.TemplateDetails.AddActivityName)
       ReportDashboardPage.getCreateNewTemplateAddPrincipleSignatureButton().click()
       ReportDashboardPage.getCreateNewTemplateVerifyAddSignatureTxt().should('have.text',this.TemplateDetails.AddSignatureTxt)
       ReportDashboardPage.getCreateNewTemplateUploadImage().selectFile(this.TemplateDetails.SignatureFile)
       ReportDashboardPage.getSaveButton().click({force:true})
       ReportDashboardPage.getCreateNewTemplateSaveAndPreviewBtn().click()
       ReportDashboardPage.getPreviewScreenSubDetailsText().then((Subjet)=>{
        expect(Subjet.text()).to.equal(this.TemplateDetails.SubDetails)
       })
       ReportDashboardPage.getPreviewScreenCoScholasticActivitiesTxt().then((ActivityName)=>{
        expect(ActivityName.text()).to.equal(this.TemplateDetails.Co_ScholasticActivities)
      })
      ReportDashboardPage.getPreviewScreenPublishButton().click()
      ReportDashboardPage.getPreviewScreenYesPublishButton().click()
      ReportDashboardPage.getStudentGradeBookTxt().should('have.text',this.TemplateDetails.StudentGradeBookTxt)
      ReportDashboardPage.getVerifyGradeContainPublishedStatus(this.TemplateDetails.Grade).should('have.text',this.TemplateDetails.PublishedStatus)
      ReportDashboardPage.getPublishedStatusToggleButton(this.TemplateDetails.Grade).click().wait(1000)
      ReportDashboardPage.getYesUnfinishButton().click()
      //cy.wait(6000)
     // ReportDashboardPage.getVerifyGradebookUnfinishedSuccesfullyTxt().should('have.contains',' Gradebook is unpublished successfully')
      ReportDashboardPage.getVerifyGradeContainDraftStatus(this.TemplateDetails.Grade).should('have.text',this.TemplateDetails.DraftStatus)
      ReportDashboardPage.getDraftStatusToggleButton(this.TemplateDetails.Grade).click()
      ReportDashboardPage.getPreviewScreenPublishButton().click()
      ReportDashboardPage.getPreviewScreenYesPublishButton().click()
      ReportDashboardPage.getVerifyGradeContainPublishedStatus(this.TemplateDetails.Grade).should('have.text',this.TemplateDetails.PublishedStatus)
      ReportDashboardPage.getPublishedStatusToggleButton(this.TemplateDetails.Grade).click().wait(1000)
      ReportDashboardPage.getYesUnfinishButton().click()
      ReportDashboardPage.getVerifyGradeContainDraftStatus(this.TemplateDetails.Grade).should('have.text',this.TemplateDetails.DraftStatus)
      ReportDashboardPage.getDraftStatusToggleButton(this.TemplateDetails.Grade).click()
      ReportDashboardPage.getPreviewScreenPublishButton().click()
      ReportDashboardPage.getPreviewScreenYesPublishButton().click()
      ReportDashboardPage.getVerifyGradeContainPublishedStatus(this.TemplateDetails.Grade).should('have.text',this.TemplateDetails.PublishedStatus)
      ReportDashboardPage.getPublishedStatusToggleButton(this.TemplateDetails.Grade).click().wait(1000)
      ReportDashboardPage.getYesUnfinishButton().click()
      ReportDashboardPage.getDeleteIcon(this.TemplateDetails.Grade).click()
      ReportDashboardPage.getDeleteButton().click()  
    })



    it.only('Tc_002 Verify that School Admin can Create the Gradebook Template',function(){

      ReportDashboardPage.getAdminReportsSideMenubarReportTab().click()
      ReportDashboardPage.getAdminReportsStudentGradebookTab().should('be.visible',{timeout:2000}).click({force:true})
      ReportDashboardPage.getAdminReportsVerifyStudentGradebookText().should('have.text',this.TemplateDetails.StudentGradebookText)
      ReportDashboardPage.getAdminReportsGradeViewButton(this.TemplateDetails.Grade).click()
      ReportDashboardPage.getCreateNewButton().click()
      ReportDashboardPage.getAdminReportsVerifyBasicTemplateDetailsText().should('have.text',this.TemplateDetails.BasicTemplateDetailsText)
      ReportDashboardPage.getCreateNewTemplateGradeDropdown().click()
      ReportDashboardPage.getCreateNewTemplateSelectGradeDropdownValue().click()
      ReportDashboardPage.getCreateNewTemplateSectionDropdown().click()
      ReportDashboardPage.getCreateNewTemplateSelectSectionDropdownValue().click()
      cy.get('body').click()
      ReportDashboardPage.getCreateNewTemplateNumberOftermsDropdown().click()
      ReportDashboardPage.getCreateNewTemplateSelectNumberOftermsValue().click()
      ReportDashboardPage.getCreateNewTemplatePublishGradebookInDropdown().click()
      ReportDashboardPage.getCreateNewTemplateSelectPublishGradebookInValue().click({force:true})
      ReportDashboardPage.getCountinueButton().click()
      ReportDashboardPage.getCreateNewTemplateAddTestTypeButton().click()
      ReportDashboardPage.getCreateNewTemplateTermDropdown().click().wait(1000)
      ReportDashboardPage.getCreateNewTemplateTermCheckbox().click()
      cy.get('body').click()
      ReportDashboardPage.getCreateNewTemplateTestTypeDropdown().click()
      ReportDashboardPage.getCreateNewTemplateSelectTestTypeValue().click()
      ReportDashboardPage.getCreateNewTemplateMaxMarksDropdown().click()
      ReportDashboardPage.getCreateNewTemplateSelectMaxMarksValue().click()
      ReportDashboardPage.getCountinueButton().click()
      ReportDashboardPage.getCreateNewTemplateAddSubjectButton().click()
       ReportDashboardPage.getCreateNewTemplateSubjectDropdown().click()
       ReportDashboardPage.getCreateNewTemplateSelectSubjectvalue().click()
       ReportDashboardPage.getCreateNewTemplateAddTheoryAndPracticleButton().click()
       ReportDashboardPage.getAddTheoryAndPracticleTestTypeDropdown().click({force:true})
       ReportDashboardPage.getAddTheoryAndPracticleTestTypeValue().click()
       ReportDashboardPage.getCreateNewTemplateTheoryTextfield().should('have.value',this.TemplateDetails.Theory)
       ReportDashboardPage.getCreateNewTemplatePracticleTextfield().click().type(this.TemplateDetails.Practicle)
       ReportDashboardPage.getCountinueButton().click()
       ReportDashboardPage.getAddActivityButton().click()
       ReportDashboardPage.getCreateNewTemplateAddActivityTextfield().type(this.TemplateDetails.AddActivityName)
       ReportDashboardPage.getCountinueButton().click()
       ReportDashboardPage.getCreateNewTemplateAddPrincipleSignatureButton().click()
       ReportDashboardPage.getCreateNewTemplateVerifyAddSignatureTxt().should('have.text',this.TemplateDetails.AddSignatureTxt)
       ReportDashboardPage.getCreateNewTemplateUploadImage().selectFile(this.TemplateDetails.SignatureFile)
       ReportDashboardPage.getSaveButton().click({force:true})
       ReportDashboardPage.getCreateNewTemplateSaveAndPreviewBtn().click()
       ReportDashboardPage.getPreviewScreenSubDetailsText().then((Subjet)=>{
        expect(Subjet.text()).to.equal(this.TemplateDetails.SubDetails)
       })
       ReportDashboardPage.getPreviewScreenCoScholasticActivitiesTxt().then((ActivityName)=>{
        expect(ActivityName.text()).to.equal(this.TemplateDetails.AddActivityName)
      })
      ReportDashboardPage.getPreviewScreenPublishButton().click()
      ReportDashboardPage.getPreviewScreenYesPublishButton().click()
      ReportDashboardPage.getStudentGradeBookTxt().should('have.text',this.TemplateDetails.StudentGradeBookTxt)
      ReportDashboardPage.getVerifyGradeContainPublishedStatus(this.TemplateDetails.Grade).should('have.text',this.TemplateDetails.PublishedStatus)
      ReportDashboardPage.getPublishedStatusToggleButton(this.TemplateDetails.Grade).click().wait(1000)
      ReportDashboardPage.getYesUnfinishButton().click()
      ReportDashboardPage.getVerifyGradeContainDraftStatus(this.TemplateDetails.Grade).should('have.text',this.TemplateDetails.DraftStatus)
      ReportDashboardPage.getDraftStatusToggleButton(this.TemplateDetails.Grade).click()
      ReportDashboardPage.getPreviewScreenPublishButton().click()
      ReportDashboardPage.getPreviewScreenYesPublishButton().click()
      ReportDashboardPage.getVerifyGradeContainPublishedStatus(this.TemplateDetails.Grade).should('have.text',this.TemplateDetails.PublishedStatus)
      ReportDashboardPage.getPublishedStatusToggleButton(this.TemplateDetails.Grade).click().wait(1000)
      ReportDashboardPage.getYesUnfinishButton().click()
      ReportDashboardPage.getVerifyGradeContainDraftStatus(this.TemplateDetails.Grade).should('have.text',this.TemplateDetails.DraftStatus)
      ReportDashboardPage.getDraftStatusToggleButton(this.TemplateDetails.Grade).click()
      ReportDashboardPage.getPreviewScreenPublishButton().click()
      ReportDashboardPage.getPreviewScreenYesPublishButton().click()
      ReportDashboardPage.getVerifyGradeContainPublishedStatus(this.TemplateDetails.Grade).should('have.text',this.TemplateDetails.PublishedStatus)
      ReportDashboardPage.getPublishedStatusToggleButton(this.TemplateDetails.Grade).click().wait(1000)
      ReportDashboardPage.getYesUnfinishButton().click()
      ReportDashboardPage.getDeleteIcon(this.TemplateDetails.Grade).click()
      ReportDashboardPage.getDeleteButton().click()  

    })


    // it('Tc_003 Verify that School Admin can Delete the Gradebook Template',function(){
    // cy.CreateNewTemplate()

    // })




    //author - manoj
})