const adminUsersPage = require('../../support/pageObjects/LMS/adminUsersPage')
const adminDashboardPage = require('../../support/pageObjects/LMS/adminDashboardPage')
const teacherOverViewPage = require('../../support/pageObjects/LMS/teacherOverViewPage')
const teacherDashboardPage = require('../../support/pageObjects/LMS/teacherDashboardPage')
const login = require('../../support/pageObjects/LMS/adminIndexPage')

const dayjs = require('dayjs')

describe("Admin Users Validation", function () {

    beforeEach(function () {
        cy.visit(Cypress.env("url"))
        cy.fixture("LMS/Credentials").then(function (validAdminLoginData) {
            cy.adminLogin(validAdminLoginData.username, validAdminLoginData.password)
        })
        cy.fixture("LMS/TeacherDetails.json").as('techerDetails')
        cy.fixture("LMS/Admin_StudentDetails.json").as('studentDetails')
    })


    it('TC_Teacher_001 Verify that School admin can add Teachers successfully when entered a valid data', function () {
        adminUsersPage.getAdminUsersSideMenuTab().click({ force: true })
        adminUsersPage.getAdminUsersTeachersTab().click()
        adminUsersPage.getAdminUsersAddTeacherBtn().should('be.visible', { timeout: 4000 }).click()
        adminUsersPage.getAdminAddNewTeacherAccountFullNameTxt().type(this.techerDetails.fullname)
        adminUsersPage.getAdminAddNewTeacherAccountEmailTxt().type(this.techerDetails.teacherMail)
        adminUsersPage.getAdminAddNewTeacherAccountDateOfBirthIcon().click()
        var day = dayjs().format('D') - 1
        adminUsersPage.getAdminAddNewTeacherAccountDateOfBirthDateBtn(day).click()
        adminUsersPage.getAdminAddNewTeacherAccountGenderDropdown().click()
        adminUsersPage.getAdminAddNewTeacherAccountGenderDropdownMaleOpt().should('be.visible', { timeout: 2000 }).click()
        adminUsersPage.getAdminAddNewTeacherAccountContactNumberTxt().type(this.techerDetails.phoneNumber)
        adminUsersPage.getAdminAddNewTeacherAccountAddressLineTxt().type(this.techerDetails.adress)
        adminUsersPage.getAdminAddNewTeacherAccountPineCodeTxt().type(this.techerDetails.pineCode).wait(5000)
        adminUsersPage.getAdminAddNewTeacherAccountBasicDetailsContinueBtn().click().wait(2000)
        adminUsersPage.getAdminAddNewTeacherAccountAcademicDetailsDepartmentDropdown().click()
        adminUsersPage.getAdminAddNewTeacherAccountAcademicDetailsDepartmentDropdownOpt().first().click()
        adminUsersPage.getAdminAddNewTeacherAccountAcademicDetailsBranchDropdown().click()
        adminUsersPage.getAdminAddNewTeacherAccountAcademicDetailsBranchDropdownOpt().first().click()
        adminUsersPage.getAdminAddNewTeacherAccountAcademicDetailsDepartmentDropdown().click({ force: true })
        adminUsersPage.getAdminAddNewTeacherAccountAcademicDetailsContineBtn().click({ force: true })
        adminUsersPage.getAdminAddNewTeacherAccountGradeSectionSelectGradeDropdown().click()
        adminUsersPage.getAdminAddNewTeacherAccountGradeSectionSelectGradeDropdownOpt('Grade 2').scrollIntoView().click()
        cy.get('body').click()
        adminUsersPage.getAdminAddNewTeacherAccountGradeSectionSelectGradeCheckBox().check()
        adminUsersPage.getAdminAddNewTeacherAccountGradeSectionClassTeacherRedioBtn().click()
        adminUsersPage.getAdminAddNewTeacherAccountGradeSectionSelectSubjectsDropdown().click()
        adminUsersPage.getAdminAddNewTeacherAccountGradeSectionSelectSubjectsDropdownOpt().first().click()
        adminUsersPage.getAdminAddNewTeacherAccountSubjectsAndSectionsContineBtn().click({ force: true })
        cy.contains(this.techerDetails.ConfermationMessage).should('be.visible')
        adminUsersPage.getTeacherDeleteBtn(this.techerDetails.fullname).click()
        adminUsersPage.getTeacherDeleteAccountBtn().click()
        adminUsersPage.getTeacherConfermationPopupDeleteBtn().click().wait(2000)
    })

    it('TC_Teacher_002 Verify that School admin can add Teachers successfully with bulk upload of data', function () {
        adminUsersPage.getAdminUsersSideMenuTab().click({ force: true })
        adminUsersPage.getAdminUsersTeachersTab().click()
        adminUsersPage.getTeacherBulkUploadBtn().click()
        cy.contains('Upload Teacher Accounts in bulk').should('be.visible')
        adminUsersPage.getTeacherUploadTeacherAccountsinbulkDownloadSampleFileLink().should('be.visible')
        adminUsersPage.getTeacherUploadTeacherAccountsinbulkSelectFileFromComputerBtn().selectFile('cypress/fixtures/LMS/users_Teacher_15-05-2023 10_19_39.xlsx', { force: true })
        adminUsersPage.getTeacherUploadTeacherAccountsinbulkImportTeacherAccounts().should('be.visible', { timeout: 2000 }).click()
        cy.contains('Teacher Accounts Imported successfully').should('be.visible')
        adminUsersPage.getTeacherDeleteBtn(this.techerDetails.fullname).click()
        adminUsersPage.getTeacherDeleteAccountBtn().click()
        adminUsersPage.getTeacherConfermationPopupDeleteBtn().click().wait(2000)

    })

    it('TC_Teacher_003 Verify that School admin can add Missing details like Department, Subjects, Class Teacher etc for the bulk uploaded teachers', function () {
        adminUsersPage.getAdminUsersSideMenuTab().click({ force: true })
        adminUsersPage.getAdminUsersTeachersTab().click()

        adminUsersPage.getAdminUsersAddTeacherBtn().should('be.visible', { timeout: 4000 }).click()
        adminUsersPage.getAdminAddNewTeacherAccountFullNameTxt().type(this.techerDetails.fullname)
        adminUsersPage.getAdminAddNewTeacherAccountEmailTxt().type(this.techerDetails.teacherMail)
        adminUsersPage.getAdminAddNewTeacherAccountDateOfBirthIcon().click()
        var day = dayjs().format('D') - 1
        adminUsersPage.getAdminAddNewTeacherAccountDateOfBirthDateBtn(day).click()
        adminUsersPage.getAdminAddNewTeacherAccountGenderDropdown().click()
        adminUsersPage.getAdminAddNewTeacherAccountGenderDropdownMaleOpt().should('be.visible', { timeout: 2000 }).click()
        adminUsersPage.getAdminAddNewTeacherAccountContactNumberTxt().type(this.techerDetails.phoneNumber)
        adminUsersPage.getAdminAddNewTeacherAccountAddressLineTxt().type(this.techerDetails.adress)
        adminUsersPage.getAdminAddNewTeacherAccountPineCodeTxt().type(this.techerDetails.pineCode).wait(5000)
        adminUsersPage.getAdminAddNewTeacherAccountBasicDetailsContinueBtn().click().wait(2000)
        adminUsersPage.getAdminAddNewTeacherAccountBasicDetailsCancelBtn().click()
        adminUsersPage.getTeacherInCompleteIcon().trigger('mouseover').invoke('show')
        cy.contains('Some profile data about this teacher is incomplete').should('be.visible')
        adminUsersPage.getTeacherEditBtn(this.techerDetails.fullname).should('be.visible')
        adminUsersPage.getTeacherResetBtn(this.techerDetails.fullname).should('be.visible')
        adminUsersPage.getTeacherViewBtn(this.techerDetails.fullname).should('be.visible')
        adminUsersPage.getTeacherDeleteBtn(this.techerDetails.fullname).should('be.visible')
        adminUsersPage.getTeacherEditBtn(this.techerDetails.fullname).click()
        adminUsersPage.getTeacherEditSaveChangesBtn().click()

        adminUsersPage.getAdminAddNewTeacherAccountAcademicDetailsDepartmentDropdown().click()
        adminUsersPage.getAdminAddNewTeacherAccountAcademicDetailsDepartmentDropdownOpt().first().click()
        adminUsersPage.getAdminAddNewTeacherAccountAcademicDetailsBranchDropdown().click()
        adminUsersPage.getAdminAddNewTeacherAccountAcademicDetailsBranchDropdownOpt().first().click()
        adminUsersPage.getAdminAddNewTeacherAccountAcademicDetailsDepartmentDropdown().click({ force: true })
        adminUsersPage.getAdminAddNewTeacherAccountAcademicDetailsContineBtn().click({ force: true })
        adminUsersPage.getAdminAddNewTeacherAccountGradeSectionSelectGradeDropdown().click()
        adminUsersPage.getAdminAddNewTeacherAccountGradeSectionSelectGradeDropdownOpt('Grade 2').scrollIntoView().click()
        cy.get('body').click()
        adminUsersPage.getAdminAddNewTeacherAccountGradeSectionSelectGradeCheckBox().check()
        adminUsersPage.getAdminAddNewTeacherAccountGradeSectionClassTeacherRedioBtn().click()
        adminUsersPage.getAdminAddNewTeacherAccountGradeSectionSelectSubjectsDropdown().click()
        adminUsersPage.getAdminAddNewTeacherAccountGradeSectionSelectSubjectsDropdownOpt().first().click()
        adminUsersPage.getAdminAddNewTeacherAccountSubjectsAndSectionsContineBtn().click({ force: true })
        adminUsersPage.getTeacherDeleteBtn(this.techerDetails.fullname).click()
        adminUsersPage.getTeacherDeleteAccountBtn().click()
        adminUsersPage.getTeacherConfermationPopupDeleteBtn().click().wait(2000)
    })

    it('TC_Teacher_004 Verify that School admin can update the teacher details successfully', function () {
        adminUsersPage.getAdminUsersSideMenuTab().click({ force: true })
        adminUsersPage.getAdminUsersTeachersTab().click()
        adminUsersPage.getAdminUsersAddTeacherBtn().should('be.visible', { timeout: 4000 }).click()
        adminUsersPage.getAdminAddNewTeacherAccountFullNameTxt().type(this.techerDetails.fullname)
        adminUsersPage.getAdminAddNewTeacherAccountEmailTxt().type(this.techerDetails.teacherMail)
        adminUsersPage.getAdminAddNewTeacherAccountDateOfBirthIcon().click()
        var day = dayjs().format('D') - 1
        adminUsersPage.getAdminAddNewTeacherAccountDateOfBirthDateBtn(day).click()
        adminUsersPage.getAdminAddNewTeacherAccountGenderDropdown().click()
        adminUsersPage.getAdminAddNewTeacherAccountGenderDropdownMaleOpt().should('be.visible', { timeout: 2000 }).click()
        adminUsersPage.getAdminAddNewTeacherAccountContactNumberTxt().type(this.techerDetails.phoneNumber)
        adminUsersPage.getAdminAddNewTeacherAccountAddressLineTxt().type(this.techerDetails.adress)
        adminUsersPage.getAdminAddNewTeacherAccountPineCodeTxt().type(this.techerDetails.pineCode).wait(5000)
        adminUsersPage.getAdminAddNewTeacherAccountBasicDetailsContinueBtn().click().wait(2000)
        adminUsersPage.getAdminAddNewTeacherAccountAcademicDetailsDepartmentDropdown().click()
        adminUsersPage.getAdminAddNewTeacherAccountAcademicDetailsDepartmentDropdownOpt().first().click()
        adminUsersPage.getAdminAddNewTeacherAccountAcademicDetailsBranchDropdown().click()
        adminUsersPage.getAdminAddNewTeacherAccountAcademicDetailsBranchDropdownOpt().first().click()
        adminUsersPage.getAdminAddNewTeacherAccountAcademicDetailsDepartmentDropdown().click({ force: true })
        adminUsersPage.getAdminAddNewTeacherAccountAcademicDetailsContineBtn().click({ force: true })
        adminUsersPage.getAdminAddNewTeacherAccountGradeSectionSelectGradeDropdown().click()
        adminUsersPage.getAdminAddNewTeacherAccountGradeSectionSelectGradeDropdownOpt('Grade 2').scrollIntoView().click()
        cy.get('body').click()
        adminUsersPage.getAdminAddNewTeacherAccountGradeSectionSelectGradeCheckBox().check()
        adminUsersPage.getAdminAddNewTeacherAccountGradeSectionClassTeacherRedioBtn().click()
        adminUsersPage.getAdminAddNewTeacherAccountGradeSectionSelectSubjectsDropdown().click()
        adminUsersPage.getAdminAddNewTeacherAccountGradeSectionSelectSubjectsDropdownOpt().first().click()
        adminUsersPage.getAdminAddNewTeacherAccountSubjectsAndSectionsContineBtn().click({ force: true })
        cy.contains(this.techerDetails.ConfermationMessage).should('be.visible')

        adminUsersPage.getTeacherEditBtn(this.techerDetails.fullname).should('be.visible').click()
        adminUsersPage.getAdminAddNewTeacherAccountFullNameTxt().clear().type(this.techerDetails.fullname)
        adminUsersPage.getTeacherEditSaveChangesBtn().click().wait(2000)
        adminUsersPage.getAdminAddNewTeacherAccountAcademicDetailsContineBtn().click({ force: true }).wait(2000)
        adminUsersPage.getAdminAddNewTeacherAccountSubjectsAndSectionsContineBtn().click({ force: true }).wait(2000)
        adminUsersPage.getTeacherDeleteBtn(this.techerDetails.fullname).click()
        adminUsersPage.getTeacherDeleteAccountBtn().click()
        adminUsersPage.getTeacherConfermationPopupDeleteBtn().click().wait(2000)
    })

    it('TC_Teacher_005 Verify that School admin can Verify the teacher details with search, Filtesr and Verify pagination', function () {
        adminUsersPage.getAdminUsersSideMenuTab().click({ force: true })
        adminUsersPage.getAdminUsersTeachersTab().click()
        adminUsersPage.getAdminUsersAddTeacherBtn().should('be.visible', { timeout: 4000 }).click()
        adminUsersPage.getAdminAddNewTeacherAccountFullNameTxt().type(this.techerDetails.fullname)
        adminUsersPage.getAdminAddNewTeacherAccountEmailTxt().type(this.techerDetails.teacherMail)
        adminUsersPage.getAdminAddNewTeacherAccountDateOfBirthIcon().click()
        var day = dayjs().format('D') - 1
        adminUsersPage.getAdminAddNewTeacherAccountDateOfBirthDateBtn(day).click()
        adminUsersPage.getAdminAddNewTeacherAccountGenderDropdown().click()
        adminUsersPage.getAdminAddNewTeacherAccountGenderDropdownMaleOpt().should('be.visible', { timeout: 2000 }).click()
        adminUsersPage.getAdminAddNewTeacherAccountContactNumberTxt().type(this.techerDetails.phoneNumber)
        adminUsersPage.getAdminAddNewTeacherAccountAddressLineTxt().type(this.techerDetails.adress)
        adminUsersPage.getAdminAddNewTeacherAccountPineCodeTxt().type(this.techerDetails.pineCode).wait(5000)
        adminUsersPage.getAdminAddNewTeacherAccountBasicDetailsContinueBtn().click().wait(2000)
        adminUsersPage.getAdminAddNewTeacherAccountAcademicDetailsDepartmentDropdown().click()
        adminUsersPage.getAdminAddNewTeacherAccountAcademicDetailsDepartmentDropdownOpt().first().click()
        adminUsersPage.getAdminAddNewTeacherAccountAcademicDetailsBranchDropdown().click()
        adminUsersPage.getAdminAddNewTeacherAccountAcademicDetailsBranchDropdownOpt().first().click()
        adminUsersPage.getAdminAddNewTeacherAccountAcademicDetailsDepartmentDropdown().click({ force: true })
        adminUsersPage.getAdminAddNewTeacherAccountAcademicDetailsContineBtn().click({ force: true })
        adminUsersPage.getAdminAddNewTeacherAccountGradeSectionSelectGradeDropdown().click()
        adminUsersPage.getAdminAddNewTeacherAccountGradeSectionSelectGradeDropdownOpt('Grade 2').scrollIntoView().click()
        cy.get('body').click()
        adminUsersPage.getAdminAddNewTeacherAccountGradeSectionSelectGradeCheckBox().check()
        adminUsersPage.getAdminAddNewTeacherAccountGradeSectionClassTeacherRedioBtn().click()
        adminUsersPage.getAdminAddNewTeacherAccountGradeSectionSelectSubjectsDropdown().click()
        adminUsersPage.getAdminAddNewTeacherAccountGradeSectionSelectSubjectsDropdownOpt().first().click()
        adminUsersPage.getAdminAddNewTeacherAccountSubjectsAndSectionsContineBtn().click({ force: true })
        cy.contains(this.techerDetails.ConfermationMessage).should('be.visible')

        adminUsersPage.getTeacherViewBtn(this.techerDetails.fullname).should('be.visible', { timeout: 2000 }).click()
        adminUsersPage.getTeacherViewDeactivateAccountBtn().should('be.visible')
        adminUsersPage.getTeacherViewTeacherDetailsTab().should('be.visible')
        adminUsersPage.getTeacherViewAcademicDetailsTab().should('be.visible')
        adminUsersPage.getTeacherViewViewTeacherCalendarTab().should('be.visible')
        adminUsersPage.getTeacherViewPopupCloseBtn().click()
        adminUsersPage.getTeacherEditBtn(this.techerDetails.fullname).should('be.visible')

        adminUsersPage.getTeacherSearchTxtfld().type(this.techerDetails.fullname)
        adminUsersPage.getTeacherDeleteBtn(this.techerDetails.fullname).click()
        adminUsersPage.getTeacherDeleteAccountBtn().click()
        adminUsersPage.getTeacherConfermationPopupDeleteBtn().click().wait(2000)

    })



    it('TC_Teacher_006 Verify that Teacher in Active status can login successfully after creation added to Users list', function () {
        adminUsersPage.getAdminUsersSideMenuTab().click({ force: true })
        adminUsersPage.getAdminUsersTeachersTab().click()
        adminUsersPage.getAdminUsersAddTeacherBtn().should('be.visible', { timeout: 4000 }).click()
        adminUsersPage.getAdminAddNewTeacherAccountFullNameTxt().type(this.techerDetails.fullname)
        adminUsersPage.getAdminAddNewTeacherAccountEmailTxt().type(this.techerDetails.teacherMail)
        adminUsersPage.getAdminAddNewTeacherAccountDateOfBirthIcon().click()
        var day = dayjs().format('D') - 1
        adminUsersPage.getAdminAddNewTeacherAccountDateOfBirthDateBtn(day).click()
        adminUsersPage.getAdminAddNewTeacherAccountGenderDropdown().click()
        adminUsersPage.getAdminAddNewTeacherAccountGenderDropdownMaleOpt().should('be.visible', { timeout: 2000 }).click()
        adminUsersPage.getAdminAddNewTeacherAccountContactNumberTxt().type(this.techerDetails.phoneNumber)
        adminUsersPage.getAdminAddNewTeacherAccountAddressLineTxt().type(this.techerDetails.adress)
        adminUsersPage.getAdminAddNewTeacherAccountPineCodeTxt().type(this.techerDetails.pineCode).wait(5000)
        adminUsersPage.getAdminAddNewTeacherAccountBasicDetailsContinueBtn().click().wait(2000)
        adminUsersPage.getAdminAddNewTeacherAccountAcademicDetailsDepartmentDropdown().click()
        adminUsersPage.getAdminAddNewTeacherAccountAcademicDetailsDepartmentDropdownOpt().first().click()
        adminUsersPage.getAdminAddNewTeacherAccountAcademicDetailsBranchDropdown().click()
        adminUsersPage.getAdminAddNewTeacherAccountAcademicDetailsBranchDropdownOpt().first().click()
        adminUsersPage.getAdminAddNewTeacherAccountAcademicDetailsDepartmentDropdown().click({ force: true })
        adminUsersPage.getAdminAddNewTeacherAccountAcademicDetailsContineBtn().click({ force: true })
        adminUsersPage.getAdminAddNewTeacherAccountGradeSectionSelectGradeDropdown().click()
        adminUsersPage.getAdminAddNewTeacherAccountGradeSectionSelectGradeDropdownOpt('Grade 2').scrollIntoView().click()
        cy.get('body').click()
        adminUsersPage.getAdminAddNewTeacherAccountGradeSectionSelectGradeCheckBox().check()
        adminUsersPage.getAdminAddNewTeacherAccountGradeSectionClassTeacherRedioBtn().click()
        adminUsersPage.getAdminAddNewTeacherAccountGradeSectionSelectSubjectsDropdown().click()
        adminUsersPage.getAdminAddNewTeacherAccountGradeSectionSelectSubjectsDropdownOpt().first().click()
        adminUsersPage.getAdminAddNewTeacherAccountSubjectsAndSectionsContineBtn().click({ force: true })
        cy.contains(this.techerDetails.ConfermationMessage).should('be.visible')


        adminUsersPage.getTeacherAdmissionNumber(this.techerDetails.fullname).then(($ele) => {
            var teacherUserName = $ele.text()
            cy.wrap(teacherUserName).as('teacherUserName')
        })
        adminDashboardPage.logout()
        cy.get('@teacherUserName').then((teacherUserName) => {
            cy.teacherLogin(teacherUserName, this.techerDetails.teacherPassword)
            teacherOverViewPage.getTeacherSetNewPasswordPopupContinueBtn().click()
            teacherOverViewPage.getTeacherSetNewPasswordPasswordTxt().type(this.techerDetails.teacherPassword)
            teacherOverViewPage.getTeacherSetNewPasswordRetypePasswordTxt().type(this.techerDetails.teacherPassword)
            teacherOverViewPage.getTeacherSetNewPasswordLoginBtn().click()
            teacherOverViewPage.getTeacherLoginDetailsSetSuccessfullyPopUpGobackTologinBtn().click()
            login.getUserNameTxtFld().clear().type(teacherUserName)
            login.getPasswordTxtFld().clear().type(this.techerDetails.teacherPassword)
            login.getLogInBtn().click().wait(2000)
            teacherOverViewPage.getTeacherWalkthroughPopupCloseIcon().click()
            teacherOverViewPage.getTeacherOverViewContinueBtn().click().wait(1000)
            teacherOverViewPage.getTeacherOverViewContinueBtn().click().wait(1000)
            teacherOverViewPage.getTeacherOverViewContinueBtn().click().wait(3000)
            teacherDashboardPage.getDashboardTitle().should('have.text', 'Your Dashboard')
        })
        teacherDashboardPage.teacherLogout()
        cy.fixture("LMS/Credentials").then(function (validAdminLoginData) {
            cy.adminLogin(validAdminLoginData.username, validAdminLoginData.password)
        })
        adminUsersPage.getAdminUsersSideMenuTab().click({ force: true })
        adminUsersPage.getAdminUsersTeachersTab().click()
        adminUsersPage.getTeacherDeleteBtn(this.techerDetails.fullname).click()
        adminUsersPage.getTeacherDeactivateAccountBtn().click()
        adminUsersPage.getTeacherConfermationPopupDeactivateaccountBtn().click()
        cy.wait(5000)
        adminDashboardPage.logout()
        cy.get('@teacherUserName').then((teacherUserName) => {
            cy.teacherLogin(teacherUserName, this.techerDetails.teacherPassword)
        })
        cy.contains('Uh oh! Invalid username or password').should('be.visible')
        cy.go('back')
        cy.fixture("LMS/Credentials").then(function (validAdminLoginData) {
            cy.adminLogin(validAdminLoginData.username, validAdminLoginData.password)
        })
        adminUsersPage.getAdminUsersSideMenuTab().click({ force: true })
        adminUsersPage.getAdminUsersTeachersTab().click()
        adminUsersPage.getTeacherDeactivateBtn(this.techerDetails.fullname).click()
        adminUsersPage.getTeacherDeactivateActivateBtn().click()
        adminUsersPage.getTeacherDeactivatePopupActivateBtn().click()
        cy.wait(5000)
        adminDashboardPage.logout()
        cy.get('@teacherUserName').then((teacherUserName) => {
            cy.teacherLogin(teacherUserName, this.techerDetails.teacherPassword)
        })
        teacherDashboardPage.getDashboardTitle().should('have.text', 'Your Dashboard')
        teacherDashboardPage.teacherLogout()
        cy.fixture("LMS/Credentials").then(function (validAdminLoginData) {
            cy.adminLogin(validAdminLoginData.username, validAdminLoginData.password)
        })
        adminUsersPage.getAdminUsersSideMenuTab().click({ force: true })
        adminUsersPage.getAdminUsersTeachersTab().click()
        adminUsersPage.getTeacherDeleteBtn(this.techerDetails.fullname).click()
        adminUsersPage.getTeacherDeleteAccountBtn().click()
        adminUsersPage.getTeacherConfermationPopupDeleteBtn().click().wait(2000)
    })


    it('TC_Student_007 Verify that School admin can add Students successfully when entered a valid data', function () {
        adminUsersPage.getAdminUsersSideMenuTab().click({ force: true })
        adminUsersPage.getAdminUsersStudentTab().click()
        adminUsersPage.getStudentSearchTxtfld().should('be.visible')
        adminUsersPage.getAddtudentBtn().click()
        adminUsersPage.getStudentFullNameTxtFld().type(this.studentDetails.studentName)
        adminUsersPage.getStudentGenderDropDown().click()
        adminUsersPage.getStudentGenderDropDownOpt().first().click()
        adminUsersPage.getStudentContactNumberTxtFld().type(this.studentDetails.studentContactNumber)
        adminUsersPage.getStudentRelationDropDown().click()
        adminUsersPage.getStudentRelationDropDownOpt().first().click()
        adminUsersPage.getStudentGurdianNameTxtFld().type(this.studentDetails.StudentFatherName)
        adminUsersPage.getStudentGurdianContactNumberTxtFld().type(this.studentDetails.studentFatherContactNumber)
        adminUsersPage.getStudentAddressTxtFld().type(this.studentDetails.studentAddress)
        adminUsersPage.getStudentPinecodeTxtFld().type(this.studentDetails.studentPinecode)
        adminUsersPage.getAddStudentBtn().click()
        cy.wait(2000)
        adminUsersPage.getStudentAcademicDetailsAmissionYearTxtFld().type(dayjs().format('YYYY'),{force:true})
        adminUsersPage.getStudentAcademicDetailsAdmissionNumberTxtFld().type(this.studentDetails.studentAddmissionNumber).wait(2000)
        adminUsersPage.getStudentAcademicDetailsGradeDropdown().click({force:true})
        adminUsersPage.getStudentAcademicDetailsGradeDropdownOpt(this.studentDetails.studentGrade).click()
        adminUsersPage.getStudentAcademicDetailsSectionsDropdown().click({force:true})
        adminUsersPage.getStudentAcademicDetailsSectionDropdownOpt().first().click()
        adminUsersPage.getStudentAcademicDetailsRollNoTxtFld().type(this.studentDetails.studentRollNo)
        adminUsersPage.getAddStudentBtn().click().wait(2000)
        adminUsersPage.getStudentDeleteBtn(this.studentDetails.student).click()
        adminUsersPage.getStudentDeleteAccountBtn().click()
        adminUsersPage.getStudentConfermationPopupDeleteBtn().click().wait(2000)
    })

    it('TC_Student_008 Verify that School admin can bulk upload students successfully', function () {
        adminUsersPage.getAdminUsersSideMenuTab().click({ force: true })
        adminUsersPage.getAdminUsersTeachersTab().click()
        adminUsersPage.getAdminUsersStudentTab().click()
        adminUsersPage.getStudentSearchTxtfld().should('be.visible')
        adminUsersPage.getStudentBulkUploadBtn().click()
        cy.contains('Specify Grade & Section to Add Students').should('be.visible')
        adminUsersPage.getAddStudentGradeDropdown().click()
        adminUsersPage.getAddStudentGradeDropdownOpt(this.studentDetails.studentGrade).click()
        adminUsersPage.getAddStudentSectionDropdown().click()
        adminUsersPage.getAddStudentSectionDropdownOpt(this.studentDetails.studentSection).click()
        adminUsersPage.getAddStudentDoneBtn().click()
        cy.contains('Upload Student Account in bulk').should('be.visible')
        adminUsersPage.getStudentBulkUploadDownloadSampleFile().should('be.visible')
        adminUsersPage.getStudentUploadStudentAccountsinbulkSelectFileFromComputerBtn().selectFile('cypress/fixtures/LMS/users_Student_23-05-2023 10_25_49.xlsx', { force: true })
        adminUsersPage.getStudentUploadStudentAccountsinbulkImportStudentAccounts().should('be.visible', { timeout: 2000 }).click()
        cy.contains('Student Account Imported successfully').should('be.visible')
        adminUsersPage.getStudentDeleteBtn(this.studentDetails.student).click()
        adminUsersPage.getStudentDeleteAccountBtn().click()
        adminUsersPage.getStudentConfermationPopupDeleteBtn().click().wait(2000)
    })

    it('TC_Student_009 Verify that School admin can Edit the student details successfully', function () {
        adminUsersPage.getAdminUsersSideMenuTab().click({ force: true })
        adminUsersPage.getAdminUsersTeachersTab().click()
        adminUsersPage.getAdminUsersStudentTab().click()
        adminUsersPage.getStudentSearchTxtfld().should('be.visible')
        adminUsersPage.getStudentBulkUploadBtn().click()
        cy.contains('Specify Grade & Section to Add Students').should('be.visible')
        adminUsersPage.getAddStudentGradeDropdown().click()
        adminUsersPage.getAddStudentGradeDropdownOpt(this.studentDetails.studentGrade).click()
        adminUsersPage.getAddStudentSectionDropdown().click()
        adminUsersPage.getAddStudentSectionDropdownOpt(this.studentDetails.studentSection).click()
        adminUsersPage.getAddStudentDoneBtn().click()
        cy.contains('Upload Student Account in bulk').should('be.visible')
        adminUsersPage.getStudentBulkUploadDownloadSampleFile().should('be.visible')
        adminUsersPage.getStudentUploadStudentAccountsinbulkSelectFileFromComputerBtn().selectFile('cypress/fixtures/LMS/users_Student_23-05-2023 10_25_49.xlsx', { force: true })
        adminUsersPage.getStudentUploadStudentAccountsinbulkImportStudentAccounts().should('be.visible', { timeout: 2000 }).click()
        cy.contains('Student Account Imported successfully').should('be.visible')
        adminUsersPage.getStudentEditBtn(this.studentDetails.student).should('be.visible')
        adminUsersPage.getStudentViewBtn(this.studentDetails.student).should('be.visible')
        adminUsersPage.getStudentDeleteBtn(this.studentDetails.student).should('be.visible')
        adminUsersPage.getStudentEditBtn(this.studentDetails.student).click()
        adminUsersPage.getStudentEditSaveChangesBtn().click().wait(2000)
        adminUsersPage.getAdminAddNewTeacherAccountAcademicDetailsSaveChangesBtn().click({ force: true })
        adminUsersPage.getStudentDeleteBtn(this.studentDetails.student).click()
        adminUsersPage.getStudentDeleteAccountBtn().click()
        adminUsersPage.getStudentConfermationPopupDeleteBtn().click().wait(2000)
    })
})